# Generated by Django 5.2.5 on 2025-08-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Источник')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('normalized_quote', models.CharField(editable=False, max_length=255, verbose_name='Нормализованная цитата')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Вес')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Дизлайки')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'constraints': [models.UniqueConstraint(fields=('source', 'normalized_quote'), name='unique_normalized_quote_per_source'), models.CheckConstraint(condition=models.Q(('weight__gte', 1)), name='weight_gte_1')],
            },
        ),
    ]
